name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  #secrets: write

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy Docker to AWS (EC2)
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESSS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        app_port: 3000

  Documentdb:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSS_KEY_ID_SANDBOX }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws-region: us-east-1
        
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Connect to DocumentDB
      run: |
        aws docdb describe-db-instances --db-instance-identifier your-db-instance-id
        
    - name: Other DocumentDB tasks
      run: |
        # Perform other DocumentDB-related tasks using AWS CLI commands
        